### ISSUE TITLE
Subsampling pipeline

### ISSUE THREAD

**Issue by xu-ji** [optimass/Maximally_Interfered_Retrieval#2]
Hi @optimass, thank you for your interesting work.

Just to clarify the sizes. For e.g. `python er_main.py --method mir_replay --dataset split_cifar10 --mem_size 20 --subsample 50 --samples_per_task -1 --n_runs 5 --disc_iters 1 --suffix 'ER_MIR'` this seems to be the flow:

- Total buffer size: 20 * 10 classes = 200 samples ([line](https://github.com/optimass/Maximally_Interfered_Retrieval/blob/4af82d1625655391aad6ddb21608113508003a20/er_main.py#L118))
- Randomly sample 50 from the 200, from classes other than the current batch's 2 classes ([line](https://github.com/optimass/Maximally_Interfered_Retrieval/blob/6ac9c6d8e74863fff142803d85a889d7ca7e299a/mir.py#L320))
- For MIR: get top `buffer_batch_size`=10 from the 50 samples, using MIR metric to rank ([line](https://github.com/optimass/Maximally_Interfered_Retrieval/blob/6ac9c6d8e74863fff142803d85a889d7ca7e299a/mir.py#L351)). For plain ER: randomly get 10 from the 50.

Is this correct?
What is the purpose of sub-sampling 50 as opposed to ranking the top 10 from the full 200?

**Comment by optimass** [comment]
that looks correct. @eugenium can you validate?

the purpose of the subsampling is to give the user control over the computations required for the replays.

**Comment by xu-ji** [comment]
I suppose if you don't want to run the entire buffer through the network, subsampling will save on computation costs. I see. Though, would probably expect training without sub-sampling to give the best performance?

You showed that multiple iterations improves performance. I wonder if this is because it increases the effective sampling coverage of the whole buffer, since you sample afresh in each repeated iteration.

**Comment by eugenium** [comment]
Yes the calculations look correct.

About subsampling, it is not only for computational complexity, it's important to enocurage sample diversity as otherwise the same set of samples might be picked too often. I guess one could also use a diversity criteria for this but we found this way is the cleanest and addresses the issues with computational complexity for larger buffer

About mutliple iterations. It also helps in the case when sampling from the buffer is fixed after iteration 1, so it is not completely due to coverage, but it may be a factor

**Comment by xu-ji** [comment]
I see, thank you.
